Update islzma. Doesn't actually compile yet:
islzma.c(73,10): error C2039: 'numBlockThreads': is not a member of 'CLzma2EncProps'
islzma.c(95,10): warning C4013: 'Lzma2Enc_Encode' undefined; assuming extern returning int

Have to figure out what to do which these.
-numBlockThreads was split into numBlockThreads_Reduced and numBlockThreads_Max
-Lzma2Enc_Encode was renamed to Lzma2Enc_Encode2